# Generated by Django 6.0.6 on 2026-07-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_budget"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("stock", "Stock"),
                            ("etf", "ETF"),
                            ("mf", "Mutual Fund"),
                        ],
                        default="stock",
                        max_length=10,
                    ),
                ),
                (
                    "exchange",
                    models.CharField(
                        blank=True,
                        choices=[("NSE", "NSE"), ("BSE", "BSE")],
                        default="NSE",
                        max_length=5,
                    ),
                ),
                ("identifier", models.CharField(max_length=30)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=14)),
                ("buy_price", models.DecimalField(decimal_places=4, max_digits=12)),
                ("current_price", models.DecimalField(decimal_places=4, max_digits=12)),
                ("date_added", models.DateField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
